main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
name: CoinsEngine
folia-supported: true
author: NightExpress
desciption: Unlimited virtual currencies and server economy.
depend: [ nightcore ]
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - DeluxeCoinflip
load: STARTUP
api-version: 1.20